### ISSUE TITLE
are the text logos necessary for D3plus and Data USA?

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel#7]
#### Behavior

On both mobile and desktop, the first section of each portfolio page has a text title. This is great for OEC and DataViva, where the logo is an icon:
<img width="320" alt="screen shot 2016-04-16 at 5 05 20 pm" src="https://cloud.githubusercontent.com/assets/1847581/14583615/9f08d010-03f5-11e6-9d17-6e9a5bcdeaa2.png">

However, it seems redundant for Data USA and D3plus:
<img width="318" alt="screen shot 2016-04-16 at 5 04 55 pm" src="https://cloud.githubusercontent.com/assets/1847581/14583618/b9f4c01e-03f5-11e6-9b29-fe28ee52a892.png"> <img width="317" alt="screen shot 2016-04-16 at 5 05 08 pm" src="https://cloud.githubusercontent.com/assets/1847581/14583619/bc161398-03f5-11e6-8d51-e896fc5ff731.png">
#### Possible Solution

Should we hide the text logo on pages that say the name in the graphic?

**Comment by chrissim15** [comment]
In this case, I think consistency is more important than subtle redundancy. Even though some logos repeat the title, they’re still graphic elements separate from the text. They function more as the visual face of the project rather than the title, so I don’t think having both is weird. I think it would be more distracting to have a header title for some and not others.

**Comment by davelandry** [comment]
Fair points. Let's keep it the way it is.
